
project_id = "qrbrrqrtfoltgrcwramh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
# Added security measures
enable_strong_password_policy = true
min_password_length = 10
require_email_confirmation = true

# Добавляем настройки защиты от перебора
rate_limit_email_sent = 5  # Ограничение отправки электронных писем
rate_limit_sms_sent = 3    # Ограничение отправки SMS
rate_limit_authenticated_requests = 30  # Ограничение для аутентифицированных запросов
rate_limit_unauthenticated_requests = 10  # Ограничение для неаутентифицированных запросов
rate_limit_token_refresh = 5  # Ограничение для обновления токенов
rate_limit_sign_up = 3  # Ограничение на количество регистраций
rate_limit_sign_in = 5  # Ограничение на количество входов
max_sign_in_attempts_per_minute = 5  # Максимальное количество попыток входа в минуту
max_sign_in_attempts_per_hour = 15  # Максимальное количество попыток входа в час

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[experimental]
minimal_apis = false

[functions]
[functions.deepseek-chat]
verify_jwt = true  # Enable JWT verification for the function

