
# Existing configuration
project_id = "qrbrrqrtfoltgrcwramh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

# Enhanced security measures
enable_strong_password_policy = true
min_password_length = 12  # Increased from 10
require_email_confirmation = true

# Brute-force protection settings
rate_limit_email_sent = 3  # Reduced from 5
rate_limit_sms_sent = 2    # Reduced from 3
rate_limit_authenticated_requests = 20  # Reduced from 30
rate_limit_unauthenticated_requests = 5  # Reduced from 10
rate_limit_token_refresh = 3  # Reduced from 5
rate_limit_sign_up = 2  # Reduced from 3
rate_limit_sign_in = 3  # Reduced from 5
max_sign_in_attempts_per_minute = 3  # Reduced from 5
max_sign_in_attempts_per_hour = 10  # Reduced from 15

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Additional security configurations from previous version
[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[experimental]
minimal_apis = false

[functions]
[functions.deepseek-chat]
verify_jwt = true
